language: cpp

compiler:
  - clang
  - gcc

env:
  global:
    - BUILD_TYPE=Debug
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "PRd28sDM/gQgRj1MaqzEk4Gvp8gzqs5eAmdhRlS8vHehYSgnAz6aYMoYETtSK5i9d6+als/Tj/21YE/s3KwWapYkMgl2DmnbSJk7sIr2to5QbKmKWfTBgtEv0jdf6bRaXQKNIqhAkv7qsuqC39dmeSbXSaKCo/5cIPEVFjWpXh8="
  matrix:
    - DISABLE_STD=Yes CONFIG_HAS_CXX11=Yes
    - DISABLE_STD=Yes CONFIG_HAS_CXX11=No
    - DISABLE_STD=No  CONFIG_HAS_CXX11=Yes
    - DISABLE_STD=No  CONFIG_HAS_CXX11=No

before_install:
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.1-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.1-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.1.1-Linux-x86_64/* /usr
  - rm -rf cmake-3.1.1-Linux-x86_64
  - rm cmake-3.1.1-Linux-x86_64.tar.gz
  - cmake --version
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - rm gmock-1.7.0.zip


before_script:
  - mkdir build
  - cd build

script:
  - cmake ../ -DNESTL_GOOGLEMOCK_DIR=`pwd`/../gmock-1.7.0 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DNESTL_DISABLE_STD=${DISABLE_STD} -DNESTL_CONFIG_HAS_CXX11=${CONFIG_HAS_CXX11}
  - make
  - make test

branches:
  only:
    - master

# coverity scanning
addons:
  coverity_scan:
    project:
      name: "prograholic/nestl"
      description: "Build submitted via Travis CI"
    notification_email: alexey.kutumov@gmail.com
    build_command_prepend: "cmake ../ -DNESTL_GOOGLEMOCK_DIR=`pwd`/../gmock-1.7.0 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DNESTL_DISABLE_STD=${DISABLE_STD} -DNESTL_CONFIG_HAS_CXX11=${CONFIG_HAS_CXX11}"
    build_command:   "make"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients
      - alexey.kutumov@gmail.com
