language: cpp

compiler:
  - gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "PRd28sDM/gQgRj1MaqzEk4Gvp8gzqs5eAmdhRlS8vHehYSgnAz6aYMoYETtSK5i9d6+als/Tj/21YE/s3KwWapYkMgl2DmnbSJk7sIr2to5QbKmKWfTBgtEv0jdf6bRaXQKNIqhAkv7qsuqC39dmeSbXSaKCo/5cIPEVFjWpXh8="

before_install:
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.1-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.1-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.1.1-Linux-x86_64/* /usr
  - rm -rf cmake-3.1.1-Linux-x86_64
  - rm cmake-3.1.1-Linux-x86_64.tar.gz
  - cmake --version
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - rm gmock-1.7.0.zip

# coverity scanning
addons:
  coverity_scan:
    project:
      name: "prograholic/nestl"
      description: "Build submitted via Travis CI"
    notification_email: alexey.kutumov@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake ../ -DNESTL_GOOGLEMOCK_DIR=`pwd`/../gmock-1.7.0 -DCMAKE_BUILD_TYPE=Release -DNESTL_DISABLE_STD=Yes -DNESTL_CONFIG_HAS_CXX11=Yes"
    build_command:   "make"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients
      - alexey.kutumov@gmail.com
