language: cpp

compiler:
  - clang
  - gcc

env:
  global:
    - BUILD_TYPE=Debug
  matrix:
    - DISABLE_STD=Yes CONFIG_HAS_CXX11=Yes
    - DISABLE_STD=Yes CONFIG_HAS_CXX11=No
    - DISABLE_STD=No  CONFIG_HAS_CXX11=Yes
    - DISABLE_STD=No  CONFIG_HAS_CXX11=No

before_install:
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.1-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.1-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.1.1-Linux-x86_64/* /usr
  - rm -rf cmake-3.1.1-Linux-x86_64
  - rm cmake-3.1.1-Linux-x86_64.tar.gz
  - cmake --version
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - rm gmock-1.7.0.zip


before_script:
  - mkdir build
  - cd build

script:
  - cmake ../ -DNESTL_GOOGLEMOCK_DIR=`pwd`/../gmock-1.7.0 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DNESTL_DISABLE_STD=${DISABLE_STD} -DNESTL_CONFIG_HAS_CXX11=${CONFIG_HAS_CXX11}
  - make
  - make test

branches:
  only:
    - master

notifications:
  email:
    recipients
      - alexey.kutumov@gmail.com
