language: cpp

compiler:
  - clang
  - gcc

#before_install:
# - sudo apt-get update
# - sudo apt-get install libgtest-dev google-mock
# - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
#before_script:
# - pwd
#

script: "mkdir build && cd build && cmake ../ && make"
branches:
  only:
    - master

notifications:
  recipients:
    - alexey.kutumov@gmail.com
  email:
    on_success: change
    on_failure: always
